/**
 * BLOG (09/10/2026) — textos fijos del listado, la plantilla y el panel.
 * Solo en español: el blog no tiene versión inglesa en esta fase.
 * NO LITERAL: microcopy propio, sin datos factuales (regla 3).
 */
export const blogText = {
  index: {
    eyebrow: 'Actualidad',
    title: 'Blog',
    lead: 'Ferias, divulgación y vida de la compañía.',
    empty: 'Todavía no hay artículos publicados.',
    readMore: 'Leer artículo',
    metaTitle: 'Blog',
    metaDescription: 'Noticias, ferias y divulgación sobre complementos alimenticios de Laboratorios Virens.',
  },
  article: {
    back: 'Todos los artículos',
    crumbHome: 'Inicio',
    crumbBlog: 'Blog',
  },
} as const;

/** Panel interno (/admin). */
export const adminText = {
  metaTitle: 'Panel del blog',
  checking: 'Comprobando la sesión…',
  notConfigured: 'El blog todavía no está conectado a Supabase (falta la dirección o la clave en `src/config/blog.ts`).',
  login: {
    title: 'Panel del blog',
    lead: 'Entra con tu email y tu contraseña.',
    email: 'Email',
    password: 'Contraseña',
    submit: 'Entrar',
    sending: 'Entrando…',
    wrong: 'El email o la contraseña no son correctos.',
    notAdmin: 'Esta cuenta no tiene permiso para editar el blog.',
    tooMany: 'Demasiados intentos. Espera unos minutos y vuelve a probar.',
    error: 'No se ha podido entrar. Revisa la conexión y vuelve a probar.',
  },
  bar: { title: 'Blog', site: 'Ver la web', logout: 'Cerrar sesión' },
  list: {
    title: 'Artículos',
    create: 'Nueva noticia',
    empty: 'Todavía no hay artículos. Pulsa «Nueva noticia» para escribir el primero.',
    loading: 'Cargando artículos…',
    error: 'No se han podido cargar los artículos.',
    untitled: 'Sin título',
    draft: 'Borrador',
    published: 'Publicado',
    scheduled: 'Programado',
    createdOn: 'Creado el',
    publishedOn: 'Publicado el',
    scheduledFor: 'Sale el',
    edit: 'Editar',
    view: 'Ver',
  },
  editor: {
    back: 'Volver a la lista',
    newTitle: 'Nueva noticia',
    editTitle: 'Editar noticia',
    cover: 'Imagen principal',
    coverPick: 'Subir foto',
    coverChange: 'Cambiar foto',
    coverRemove: 'Quitar',
    coverUploading: 'Subiendo foto…',
    coverHint: 'JPG, PNG o WEBP. Se reduce sola a un tamaño adecuado para la web.',
    title: 'Título',
    subtitle: 'Subtítulo / entradilla',
    body: 'Cuerpo del artículo',
    bodyPlaceholder: 'Escribe o pega aquí el texto…',
    more: 'Dirección y fecha',
    slug: 'Dirección (slug)',
    slugHint: 'Se rellena sola con el título. Cámbiala solo si lo necesitas.',
    slugReset: 'Volver a la automática',
    date: 'Fecha de publicación',
    dateHint: 'Si pones una fecha futura, el artículo saldrá ese día.',
    saveDraft: 'Guardar borrador',
    publish: 'Publicar',
    update: 'Guardar cambios',
    unpublish: 'Pasar a borrador',
    delete: 'Eliminar',
    confirmDelete: '¿Eliminar este artículo? No se puede deshacer.',
    view: 'Ver en la web',
    saving: 'Guardando…',
    saved: 'Guardado.',
    publishedOk: 'Publicado. Aparecerá en la web en un minuto como mucho.',
    unpublishedOk: 'Ahora es un borrador: ya no se ve en la web.',
    loading: 'Cargando…',
    notFound: 'Este artículo no existe o ya se ha eliminado.',
    statusDraft: 'Borrador',
    statusPublished: 'Publicado',
    errors: {
      title: 'Falta el título.',
      slug: 'La dirección solo puede llevar letras sin acentos, números y guiones.',
      slugTaken: 'Ya hay otro artículo con esta dirección. Cámbiala en «Dirección y fecha».',
      cover: 'No se ha podido subir la foto. Prueba con otra o más pequeña.',
      save: 'No se ha podido guardar. Revisa la conexión y vuelve a probar.',
      session: 'La sesión ha caducado. Vuelve a entrar.',
    },
    unsaved: 'Hay cambios sin guardar. ¿Salir igualmente?',
  },
  toolbar: {
    bold: 'Negrita',
    italic: 'Cursiva',
    h2: 'Subtítulo grande (H2)',
    h3: 'Subtítulo pequeño (H3)',
    bullet: 'Lista',
    ordered: 'Lista numerada',
    link: 'Enlace',
    linkPrompt: 'Dirección del enlace (déjala vacía para quitarlo):',
    image: 'Imagen dentro del texto',
    undo: 'Deshacer',
    redo: 'Rehacer',
  },
} as const;
